package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.buildCache
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildPlugin'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildPlugin")) {
    features {
        add {
            buildCache {
                name = "gradle"
                rules = "%env.GRADLE_USER_HOME%"
            }
        }
    }
}
