package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.DockerCommandStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildZStdLinux'
accordingly, and delete the patch script.
*/
//changeBuildType(RelativeId("BuildZStdLinux")) {
//    expectSteps {
//        dockerCommand {
//            name = "Prepare docker with cross-compilers"
//            commandType = build {
//                source = content {
//                    content = """
//                        FROM ubuntu:24.04
//
//                                                RUN apt install -y --no-install-recommends \
//                                                    build-essential\
//                        gcc-aarch64-linux-gnu
//                    """.trimIndent()
//                }
//                namesAndTags = "ubuntu_with_cross_compilers:local"
//            }
//        }
//        script {
//            name = "Build x86_64"
//            scriptContent = """
//                make clean
//                 make
//
//                mkdir -p out
//                cp programs/zstd out/zstd_x86_64"
//            """.trimIndent()
//            dockerImage = "ubuntu_with_cross_compilers:local"
//        }
//        script {
//            name = "Build aarch64"
//            scriptContent = """
//                make clean
//                CC="aarch64-linux-gnu-gcc" make
//
//                mkdir -p out
//                cp programs/zstd out/zstd_aarch64"
//            """.trimIndent()
//            dockerImage = "ubuntu_with_cross_compilers:local"
//        }
//    }
//    steps {
//        update<DockerCommandStep>(0) {
//            clearConditions()
//            commandType = build {
//                source = content {
//                    content = """
//                        FROM ubuntu:24.04
//
//                        RUN apt install -y --no-install-recommends \
//                        build-essential \
//                        gcc-aarch64-linux-gnu
//                    """.trimIndent()
//                }
//                contextDir = ""
//                platform = DockerCommandStep.ImagePlatform.Any
//                namesAndTags = "ubuntu_with_cross_compilers:local"
//                commandArgs = ""
//            }
//        }
//    }
//}
