package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildPlugin'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildPlugin")) {
    expectSteps {
        gradle {
            name = "Build plugin"
            tasks = "buildPlugin"
        }
    }
    steps {
        update<GradleBuildStep>(0) {
            clearConditions()
            dockerImage = "amazoncorretto:17"
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
