package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildZStdLinux'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildZStdLinux")) {
    expectSteps {
        dockerCommand {
            name = "Prepare docker with cross-compilers"
            commandType = build {
                source = content {
                    content = """
                        FROM alpine:latest
                        
                        RUN apk add --no-cache \
                        		wget \
                        		build-base \
                        		make \
                        		build-base \
                        		make
                        
                        RUN wget -q https://musl.cc/aarch64-linux-musl-cross.tgz && \
                            tar -xzf aarch64-linux-musl-cross.tgz -C /opt && \
                            rm aarch64-linux-musl-cross.tgz
                    """.trimIndent()
                }
                namesAndTags = "alpine_with_cross_compilers:local"
            }
        }
        script {
            name = "Build x86_64"
            scriptContent = """
                make clean
                 make LDFLAGS="-static"
                
                mkdir -p "out/linux/x86_64"
                cp programs/zstd "out/linux/x86_64/zstd"
            """.trimIndent()
            dockerImage = "alpine_with_cross_compilers:local"
        }
        script {
            name = "Build aarch64"
            scriptContent = """
                make clean
                CC="/opt/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc" make LDFLAGS="-static"
                
                mkdir -p "out/linux/aarch64"
                cp programs/zstd "out/linux/aarch64/zstd"
            """.trimIndent()
            dockerImage = "alpine_with_cross_compilers:local"
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            clearConditions()
            scriptContent = """
                make clean
                 make zstd LDFLAGS="-static"
                
                mkdir -p "out/linux/x86_64"
                cp programs/zstd "out/linux/x86_64/zstd"
            """.trimIndent()
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
