package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReleaseToGithub'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReleaseToGithub")) {
    dependencies {
        expect(RelativeId("BuildAndSignPlugin")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                artifactRules = "+:signedPlugin.zip"
            }
        }
        update(RelativeId("BuildAndSignPlugin")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
                synchronizeRevisions = false
            }

            artifacts {
                buildRule = lastSuccessful("+:*")
                artifactRules = "+:signedPlugin.zip"
            }
        }

    }
}
