package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReleaseToGithub'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReleaseToGithub")) {
    expectSteps {
        script {
            name = "Fail: not a tag"

            conditions {
                doesNotMatch("%dep.JBAssignment_BuildAndSignPlugin.teamcity.build.vcs.branch.JBAssignment_JbAssignment1%", "refs/tags/.*")
            }
            scriptContent = """
                echo "##teamcity[buildStatus status='FAILURE' text='Build requires a tag, got: %dep.JBAssignment_BuildAndSignPlugin.teamcity.build.vcs.branch.JBAssignment_JbAssignment1%']"
                exit 1
            """.trimIndent()
        }
        script {
            name = "Extract tag"
            scriptContent = """
                set -xeuo pipefail
                            BRANCH="%dep.JBAssignment_BuildAndSignPlugin.teamcity.build.vcs.branch.JBAssignment_JbAssignment1%"
                TAG="${'$'}{BRANCH#refs/tags/}"
                echo "##teamcity[setParameter name='tag' value='${'$'}TAG']"
                echo "##teamcity[buildStatus text='Releasing ${'$'}TAG']"
            """.trimIndent()
        }
        dockerCommand {
            name = "Prepare docker with github-cli"
            commandType = build {
                source = content {
                    content = """
                        FROM alpine:latest
                        
                        RUN apk add --no-cache github-cli git
                    """.trimIndent()
                }
                namesAndTags = "alpine_with_github_cli"
            }
        }
        script {
            name = "Create GitHub Release"
            scriptContent = """
                set -xeuo pipefail
                            TAG="%tag%"
                
                # Convert git@github.com:owner/repo.git to owner/repo
                REPO_URL="%dep.JBAssignment_BuildAndSignPlugin.vcsroot.JBAssignment_JbAssignment1.url%"
                REPO="${'$'}{REPO_URL#*:}"
                REPO="${'$'}{REPO%.git}"
                
                gh release create "${'$'}TAG" \
                    --repo "${'$'}REPO" \
                    --title "${'$'}TAG" \
                    --generate-notes \
                    "input/signedPlugin.zip"
                
                echo "##teamcity[buildStatus text='Released ${'$'}TAG']"
            """.trimIndent()
            dockerImage = "alpine_with_github_cli"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()

            conditions {
                doesNotMatch("dep.JBAssignment_BuildAndSignPlugin.teamcity.build.vcs.branch.JBAssignment_JbAssignment1", "refs/tags/.*")
            }
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
        update<ScriptBuildStep>(1) {
            clearConditions()
            dockerImage = "alpine:latest"
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
