package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SignPlugin'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SignPlugin")) {
    expectSteps {
        script {
            name = "Prepare signer"
            scriptContent = """
                wget '%tool.signer.name%' -O signer.jar
                sha256 -c '%tool.signer.sha%' signer.jar
                if [ ${'$'}? -neq 0 ]; then
                    echo "Signer SHA mismatch"
                    exit 1;
                fi
            """.trimIndent()
        }
        script {
            name = "Sign plugin"
            scriptContent = """
                echo '%secret.key.base64%' | base64 -d > %system.teamcity.build.tempDir%/key.pem
                echo '%secret.cert.base64%' | base64 -d > %system.teamcity.build.tempDir%/chain.crt
                
                java -jar signer.jar sign \
                  -in input/plugin.zip \
                  -out output/signedPlugin.zip \
                  -cert-file "%system.teamcity.build.tempDir%/chain.crt" \
                  -key-file "%system.teamcity.build.tempDir%/key.pem" \
                  -key-pass "%secret.key.password%"
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            clearConditions()
            scriptContent = """
                echo '%secret.key.base64%' | base64 -d > %system.teamcity.build.tempDir%/key.pem
                echo '%secret.cert.base64%' | base64 -d > %system.teamcity.build.tempDir%/chain.crt
                
                mkdir -p output
                java -jar signer.jar sign \
                  -in input/plugin.zip \
                  -out output/signedPlugin.zip \
                  -cert-file "%system.teamcity.build.tempDir%/chain.crt" \
                  -key-file "%system.teamcity.build.tempDir%/key.pem" \
                  -key-pass "%secret.key.password%"
            """.trimIndent()
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
